version: '3.3'
volumes:
  docker_jenkins: {}

services:
  jenkins:
    image: jenkins/jenkins:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: '2'
          memory: 2048G
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.role == worker
    ports:
    - "8080:8080"
    volumes:
    - docker_jenkins:/var/jenkins_home

